// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FoodDeliveryApp.API.Models
{
    public partial class CategoryVM
    {
        [Key]
        public int CategoryId { get; set; }
        [StringLength(10)]
        public string Name { get; set; }

        public virtual ICollection<MealVM> Meals { get; set; }
    }
}