// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FoodDeliveryApp.API.Models
{
    public partial class MealVM
    {
        [Key]
        public int MealId { get; set; }
        public int? CategoryId { get; set; }
        [StringLength(450)]
        public string ProviderId { get; set; }
        [Required]
        [StringLength(100)]
        public string Name { get; set; }
        [Required]
        [StringLength(50)]
        public string PrepareTime { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal Price { get; set; }
        [Required]
        [StringLength(500)]
        public string Description { get; set; }
        [StringLength(150)]
        public string Picture { get; set; }

        public string CategoryName { get; set; }
        public string ProviderName { get; set; }
        public virtual CategoryVM Category { get; set; }
        public virtual ServiceProviderVM Provider { get; set; }
        public virtual ICollection<CartItemVM> CartItems { get; set; }
        public virtual ICollection<OrderDetailVM> OrderDetails { get; set; }
    }
}