// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FoodDeliveryApp.API.Models
{
    public partial class OrderVM
    {
        [Key]
        public int OrderId { get; set; }
        [StringLength(450)]
        public string CustomerId { get; set; }
        public int? CityCode { get; set; }
        [StringLength(350)]
        public string ShippingAddress { get; set; }
        public short? RevisionNumber { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ShippedDate { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? TotalAmount { get; set; }
        [Column("VAT", TypeName = "decimal(18, 2)")]
        public decimal? Vat { get; set; }
        [Column("TAX", TypeName = "decimal(18, 2)")]
        public decimal? Tax { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? Discount { get; set; }
        [StringLength(50)]
        public string OrderStatus { get; set; }
        public bool IsCheckout { get; set; }
        [StringLength(128)]
        public string CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateCreated { get; set; }

        public string CityName { get; set; }
        public string CustomerName { get; set; }
        public virtual CustomerVM Customer { get; set; }
        public virtual List<OrderDetailVM> OrderDetails { get; set; }
        public virtual ICollection<PaymentVM> Payments { get; set; }
        public virtual IEnumerable<CartItemVM> CartItems { get; set; }
    }
}