// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FoodDeliveryApp.API.Models
{
    public partial class PaymentVM
    {
        [Key]
        [StringLength(15)]
        public string TransactionRef { get; set; }
        public int? OrderId { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal Amount { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? TransactionDate { get; set; }

        public virtual OrderVM Order { get; set; }
    }
}